uploads = []
generated = []

[[outputs]]
id = "HSCzYueTU6ENNg3lAIOgW"
uri = "file://public/audio/welcome-student.mp3"
type = "audio"
title = "student-welcome-no-ya-batal"

[[outputs]]
id = "Xbml5vPjP0jGvsqCGzLn-"
uri = "file://public/audio/welcome-all.mp3"
type = "audio"
title = "playful-welcome-children"

[[outputs]]
id = "DkTjICGGXaK0v28HE3Hek"
uri = "file://public/audio/welcome-adult.mp3"
type = "audio"
title = "adult-welcome-professional"

[[outputs]]
id = "gMP21yUctDR0oZ4btsAzV"
uri = "file://MANARA-Android.tar.gz"
type = "unspecified"
title = "MANARA Android App (APK)"
